#lang racket
(define pi 3.14)
(define error "Ошибка")
(display "Вычисление площади кольца")
(newline)
(display "Введите исходные данные")
(newline)
(define (R)
  (write "Радиус кольца (см) = ")
  (read))
(define (r)
  (write "Радиус отверстия (см)")
  (read))
(define (S R r)
(display "Площадь кольца = ")
  (display (* pi (- (expt R 2) (expt r 2))))
  (display " кв.см")
  (newline))
(define (V R r)
  (if (> R r)
      (S R r)
      error))
(V (R)(r))
