#lang racket
(display "Вычисление сопротивления электрической цепи")
(newline)
(display "Введите исходные данные")
(newline)
(define (R1)
  (write "Величина первого сопротивления (Ом)=")
  (read))
(define (R2)
  (write "Величина второго сопротивления (Ом)=")
  (read))
(define (type)
  (write "Тип соединения. 1 - послед. 2 - парал.")
  (read))

(define (RP R1 R2)
  (display "Сопротивление цепи = ")
  (display (+ R1 R2))
  (display " Ом")
  (newline))

(define (RPL R1 R2)
  (display "Сопротивление цепи = ")
  (display (/(* R1 R2)(+ R1 R2)))
  (display " Ом")
  (newline))

(define (R R1 R2 type)
  (if (= type 1)
      (RP R1 R2)
      (RPL R1 R2))
  (newline))
(R (R1)(R2)(type))
