#lang racket
(display "Вычисление стоимости покупки")
(newline)
(display "Введите исходные данные")
(newline)
(define (ct)
  (write "Цена тетради (руб)")
  (read))
(define (kt)
  (write "Количество тетрадей")
  (read))
(define (ck)
  (write "Цена карандашей (руб)")
  (read))
(define (kk)
  (write "Количество карандашей")
  (read))
(define (s ct kt ck kk)
  (display "Стоимость покупки = ")
  (display (+(* ct kt)(* ck kk)))
  (display "руб ")
  (newline))
(s (ct)(kt)(ck)(kk))
