#lang racket
(display "Вычисление сопротивления электрической цепи")
(newline)
(display "Введите исходные данные")
(newline)
(define (R1)
  (write "Величина первого сопротивления (Ом)=")
  (read))
(define (R2)
  (write "Величина второго сопротивления (Ом)=")
  (read))
(define (R R1 R2)
  (display "Сопротивление цепи = ")
  (display (+ R1 R2))
  (display " Ом")
  (newline))
(R (R1)(R2))
